# Generated by Django 3.1.5 on 2021-07-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210705_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/default_blog_post_img1.png', null=True, upload_to='thumbnails/'),
        ),
    ]
