# Generated by Django 3.1.5 on 2021-02-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210214_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_blog_post_img.png', null=True, upload_to=''),
        ),
    ]
